columns:
  DATE: object
  VISIBILITY: float
  DRYBULBTEMPF: int
  WETBULBTEMPF: int
  DewPointTempF: int
  RelativeHumidity: int
  WindSpeed: int
  WindDirection: int
  StationPressure: float
  SeaLevelPressure: float
  Precip: float

drop_columns:
  - DATE 
  - WETBULBTEMPF 
  - DewPointTempF 
  - StationPressure
  - Precip

outlier_columns:
  - WindSpeed
  - SeaLevelPressure
